version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://root:example@mongo:27017/optimizer?authSource=admin
      JWT_SECRET: change_me
      JWT_REFRESH_SECRET: change_me_refresh
    ports:
      - "8080:8080"
volumes:
  mongo_data:
